version: '3.5'
services:
  traefik_init:
    image: <traefik version>
    command:
    - "storeconfig"
    - "--api"
    - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
    - "--entrypoints=Name:https Address::443 TLS"
    - "--default—Éntrypoints=http,https"
    - "--acme"
    - "--acme.storage=traefik/acme/account"
    - "--acme.entryPoint=https"
    - "--acme.httpChallenge.entryPoint=http"
    - "--acme.onHostRule=true"
    - "--acme.onDemand=false"
    - "--acme.email=<your email>"
    - "--docker"
    - "--docker.swarmMode"
    - "--docker.domain=<your domain>"
    - "--docker.watch"
    - "--consul"
    - "--consul.endpoint=consul:8500"
    - "--consul.prefix=traefik"
    networks:
    - traefik
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
    - consul
  traefik:
    image: <traefik version>
    depends_on:
    - traefik_init
    - consul
    command:
    - "--consul"
    - "--consul.endpoint=consul:8500"
    - "--consul.prefix=traefik"
    - "--logLevel=info"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - webgateway
    - traefik
    ports:
    - target: 80
      published: 80
      mode: host
    - target: 443
      published: 443
      mode: host
    - target: 8080
      published: 8080
      mode: host
    deploy:
      mode: global
      placement:
        constraints:
        - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  consul:
    image: consul
    command: agent -server -bootstrap-expect=1
    volumes:
    - consul-data:/consul/data
    environment:
    - CONSUL_LOCAL_CONFIG={"datacenter":"untill","server":true}
    - CONSUL_BIND_INTERFACE=eth0
    - CONSUL_CLIENT_INTERFACE=eth0
    ports:
    - 8500:8500
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
    - traefik

networks:
  traefik:
    external: true
  webgateway:
    external: true

volumes:
  consul-data:
    name: consul