groups:
- name: /1/store/projects/vagrant/docker-swarm-vagrant/apps/swarmprom/prometheus/rules/swarm_node.rules.yml
  rules:
  - alert: node_cpu_usage
    expr: 100 - (avg(irate(node_cpu_seconds_total{mode="idle"}[1m]) * ON(instance) GROUP_LEFT(node_name)
      node_meta * 100) BY (node_name)) > 50
    for: 1m
    labels:
      severity: warning
    annotations:
      description: "Swarm node {{ $labels.node_name }} CPU usage is at {{ humanize
        $value}}%."
      identifier: "CPU alert for Swarm node {{ $labels.node_name }}"
  - alert: node_memory_usage
    expr: sum(((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes)
      * ON(instance) GROUP_LEFT(node_name) node_meta * 100) BY (node_name) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      description: 'Swarm node {{ $labels.node_name }} memory usage is at {{ humanize
        $value}}%.'
      identifier: 'Memory alert for Swarm node {{ $labels.node_name }}'
  - alert: node_disk_usage
    expr: ((node_filesystem_size_bytes - node_filesystem_free_bytes)
      * 100 / node_filesystem_size_bytes) * ON(instance) GROUP_LEFT(node_name)
      node_meta > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      description: "Swarm node {{ $labels.node_name }} disk usage is at {{ humanize
        $value}}%."
      identifier: "Disk alert for Swarm node {{ $labels.node_name }}"
  - alert: node_disk_fill_rate_6h
    expr: predict_linear(node_filesystem_free_bytes[1h], 6 * 3600) * ON(instance)
      GROUP_LEFT(node_name) node_meta < 0
    for: 1h
    labels:
      severity: critical
    annotations:
      description: "Swarm node {{ $labels.node_name }} disk is going to fill up in
        6h."
      identifier: "Disk fill alert for Swarm node {{ $labels.node_name }}"
  - alert: service_down
    expr: up == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      identifier: "Instance {{ $labels.node_name }} down"
      description: "{{ $labels.node_name }} job {{ $labels.job }} has been down for more than 2 minutes."
