# ************************************************************
#
# Organization Parameters
#
#

# This parameter will be used as a parameter to create SSH certificate
Organization: !!!CHANGEME_ORGANIZATION_NAME

# Used to name SSH certificate
Cluster: !!!CHANGEME_ORGANIZATION_NAME

# This user will be used to create ClusterUser, after that this account will be disabled
# Password login for this user MUST be enabled
# This user MUST be able to run "sudo" commands without password
RootUser: untilltest

# This user will be created on each node and given sudo permissions
ClusterUser: cluster

# ************************************************************
#
# Keys Location
#
#

# Default for public key is ${HOME}/.ssh/${Cluster}
#PublicKey:

# Default for private key is ${HOME}/.ssh/${Cluster}.pub
#PrivateKey:


# ************************************************************
#
# Software Versions
#
#

# For Bionic Beaver
#Docker: 18.06.1~ce~3-0~ubuntu

#For Cosmic
#Docker:5:18.09.2~3-0~ubuntu-cosmic

# Containers without prefix "prom/" cause of we recreates them on each host with prefix {{.OrganizationName}}. Look at
# alertmanager/Dockerfile and node-exporter/Dockerfile for more

Alertmanager: prom/alertmanager:v0.15.3
NodeExporter: stefanprodan/swarmprom-node-exporter:v0.16.0
Grafana: grafana/grafana:5.3.4
Prometheus: prom/prometheus:v2.5.0
Traefik: kindratte/traefik:1.0
Cadvisor: google/cadvisor:v0.31.0
Consul: consul:1.4.2
Elasticsearch: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4
Filebeat: kindratte/filebeat:6.5.4
Kibana: docker.elastic.co/kibana/kibana-oss:6.5.4
Logstash: docker.elastic.co/logstash/logstash-oss:6.5.4
Curator: kindratte/curator:5.4

# ************************************************************
#
# ACME configuration
#
#

# If enabled
#   - ACME will be used through letsencrypt provider
#   - traefik.yml is used to configure traefik, otherwise traefik-http.yml

#ACMEEnabled: true

# If ACME is enabled the following paramaters are required

#Domain:
#Email:

# ************************************************************
#
# Credentials
#
#

# Grafana User Name
GrafanaUser: admin

# Prometheus User Name
PrometheusUser: admin

# Traefik User Name
TraefikUser: admin

# ************************************************************
#
# Alertmanager configuration
#
#

ChannelName: cluster
AlertmanagerUser: alertmanager