version: "3.5"

volumes:
  consul: {}

configs:
  agent:
    file: ./agent/conf3.json
  server:
    file: ./server/conf3.json

services:

  consul_main_server1:
    image: {{.Consul}}
    command: "consul agent -config-file /consul/config/conf.json"
    volumes:
      - consul:/consul/data
    configs:
      - source: server
        target: /consul/config/conf.json
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.id == {{.NodeID1}}
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
    networks:
      traefik:
        aliases:
          - consul_main

  consul_main_server2:
    image: {{.Consul}}
    command: "consul agent -config-file /consul/config/conf.json"
    volumes:
      - consul:/consul/data
    configs:
      - source: server
        target: /consul/config/conf.json
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.id == {{.NodeID2}}
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
    networks:
      traefik:
        aliases:
          - consul_main

  consul_main_server3:
    image: {{.Consul}}
    command: "consul agent -config-file /consul/config/conf.json"
    volumes:
      - consul:/consul/data
    configs:
      - source: server
        target: /consul/config/conf.json
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.id == {{.NodeID3}}
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
    networks:
      traefik:
        aliases:
          - consul_main

  consul_server:
    image: {{.Consul}}
    command: "consul agent -config-file /consul/config/conf.json"
    volumes:
      - consul:/consul/data
    configs:
      - source: server
        target: /consul/config/conf.json
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
          - node.id != {{.NodeID1}}
          - node.id != {{.NodeID2}}
          - node.id != {{.NodeID3}}
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
    networks:
      - traefik

  consul_agent:
    image: {{.Consul}}
    command: "consul agent -config-file /consul/config/conf.json"
    volumes:
      - consul:/consul/data
    configs:
      - source: agent
        target: /consul/config/conf.json
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
    networks:
      - traefik

networks:
  traefik:
    external: true